name: presentationcoach
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49787
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efe7dd'
    - '#502a24'
    - '#9e9182'
    - '#645a51'
    - '#ab5b63'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
